plugins { id 'com.android.application' }

android {
    namespace 'com.infinix.smart10.fastlock'
    compileSdk 35
    defaultConfig {
        applicationId 'com.infinix.smart10.fastlock'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.biometric:biometric:1.1.0'
}
