plugins { id 'com.android.application' }

android {
    namespace 'com.infinix.smart10.fastlock'
    compileSdk 35
    defaultConfig {
        applicationId 'com.infinix.smart10.fastlock'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}