package com.infinix.smart10.fastlock;

import androidx.fragment.app.FragmentActivity; import android.os.Bundle; import android.view.Gravity; import android.view.WindowManager; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.content.Intent; import android.widget.*;

public class AuthActivity extends FragmentActivity {
private android.content.SharedPreferences prefs; private EditText pass;
@Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);prefs=getSharedPreferences("fastlock",MODE_PRIVATE);buildUi();}
private void buildUi(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(42,38,42,38);GradientDrawable bg=new GradientDrawable();bg.setColor(0xF20B0E14);bg.setCornerRadius(38);box.setBackground(bg);
TextView title=new TextView(this);title.setText("FastLockApp");title.setTextColor(Color.WHITE);title.setTextSize(23);title.setGravity(Gravity.CENTER);TextView sub=new TextView(this);sub.setText("\nFastLock Fingerprint or your FastLock PIN\n\nThis credential belongs only to FastLockApp.");sub.setTextColor(0xFFB9BEC8);sub.setGravity(Gravity.CENTER);
Button fingerprint=new Button(this);fingerprint.setText("Use FastLock Fingerprint");fingerprint.setOnClickListener(v->{Intent i=new Intent(this,FingerprintSetupActivity.class);i.putExtra("verify",true);startActivityForResult(i,77);});
pass=new EditText(this);pass.setHint("FastLock PIN");pass.setInputType(2);pass.setTextColor(Color.WHITE);pass.setHintTextColor(0xFF777D88);pass.setGravity(Gravity.CENTER);
Button unlock=new Button(this);unlock.setText("Unlock with FastLock PIN");unlock.setOnClickListener(v->{if(checkPasscode(pass.getText().toString()))finish();else{pass.setError("Incorrect FastLock PIN");pass.setText("");}});
box.addView(title);box.addView(sub);if(prefs.getBoolean("app_fingerprint_set",false))box.addView(fingerprint);box.addView(pass,new LinearLayout.LayoutParams(-1,-2));box.addView(unlock);setContentView(box);}
private boolean checkPasscode(String value){try{String salt=prefs.getString("passcode_salt",""),expected=prefs.getString("passcode_hash","");if(salt.isEmpty()||expected.isEmpty())return false;javax.crypto.spec.PBEKeySpec spec=new javax.crypto.spec.PBEKeySpec(value.toCharArray(),salt.getBytes(java.nio.charset.StandardCharsets.UTF_8),120000,256);byte[] out=javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();String actual=android.util.Base64.encodeToString(out,android.util.Base64.NO_WRAP);return java.security.MessageDigest.isEqual(actual.getBytes(java.nio.charset.StandardCharsets.UTF_8),expected.getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(Exception e){return false;}}
@Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==77&&c==RESULT_OK)finish();}
}