package com.infinix.smart10.fastlock;
import android.app.*; import android.content.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*;
public class FastOverlayService extends Service {
private WindowManager wm; private View iconView,authView; private BroadcastReceiver screenReceiver; private final Handler handler=new Handler(Looper.getMainLooper());
@Override public void onCreate(){super.onCreate();startForeground(91,notification());wm=(WindowManager)getSystemService(WINDOW_SERVICE);registerScreenReceiver();}
private Notification notification(){String channel="fastlock";if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(channel,"FastLockApp",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}return new Notification.Builder(this,channel).setSmallIcon(android.R.drawable.ic_lock_lock).setContentTitle("FastLockApp active").setContentText("App-owned lock layer is active").setOngoing(true).build();}
private void registerScreenReceiver(){screenReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(Intent.ACTION_SCREEN_OFF.equals(i.getAction()))hideAll();else if(Intent.ACTION_SCREEN_ON.equals(i.getAction())&&getSharedPreferences("fastlock",MODE_PRIVATE).getBoolean("active",false))handler.postDelayed(()->showIcon(),350);}};IntentFilter f=new IntentFilter();f.addAction(Intent.ACTION_SCREEN_OFF);f.addAction(Intent.ACTION_SCREEN_ON);if(Build.VERSION.SDK_INT>=33)registerReceiver(screenReceiver,f,RECEIVER_NOT_EXPORTED);else registerReceiver(screenReceiver,f);}
private int type(){return Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;}
private WindowManager.LayoutParams lp(int w,int h,int gravity){WindowManager.LayoutParams p=new WindowManager.LayoutParams(w,h,type(),WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,android.graphics.PixelFormat.TRANSLUCENT);p.gravity=gravity;return p;}
private void showIcon(){if(!Settings.canDrawOverlays(this)||authView!=null||iconView!=null)return;TextView icon=new TextView(this);icon.setText("⌾");icon.setTextColor(Color.WHITE);icon.setTextSize(27);icon.setGravity(Gravity.CENTER);GradientDrawable bg=new GradientDrawable();bg.setColor(0xCC171A21);bg.setShape(GradientDrawable.OVAL);bg.setStroke(2,0xFFD8B35A);icon.setBackground(bg);icon.setAlpha(0f);icon.setOnClickListener(v->showAuth());iconView=icon;wm.addView(iconView,lp(76,76,Gravity.CENTER));icon.animate().alpha(1f).setDuration(900).withEndAction(()->handler.postDelayed(()->{if(iconView!=null)iconView.animate().alpha(0f).setDuration(600).withEndAction(this::removeIcon).start();},2400)).start();}
private void removeIcon(){if(iconView!=null){try{wm.removeView(iconView);}catch(Exception ignored){}iconView=null;}}
private void showAuth(){removeIcon();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(36,36,36,36);GradientDrawable bg=new GradientDrawable();bg.setColor(0xF20B0E14);bg.setCornerRadius(38);box.setBackground(bg);TextView title=new TextView(this);title.setText("FastLockApp");title.setTextColor(Color.WHITE);title.setTextSize(21);title.setGravity(Gravity.CENTER);TextView sub=new TextView(this);sub.setText("\nTouch the fingerprint-style button, or use your app passcode.");sub.setTextColor(0xFFB9BEC8);sub.setGravity(Gravity.CENTER);Button touch=new Button(this);touch.setText("Fingerprint-style touch");touch.setOnClickListener(v->{Toast.makeText(this,"App touch verified",Toast.LENGTH_SHORT).show();unlock();});EditText pass=new EditText(this);pass.setHint("App passcode");pass.setInputType(2);pass.setTextColor(Color.WHITE);pass.setHintTextColor(0xFF777D88);pass.setGravity(Gravity.CENTER);Button unlock=new Button(this);unlock.setText("Unlock");unlock.setOnClickListener(v->{if("7924".contentEquals(pass.getText()))unlock();else{pass.setError("Incorrect app passcode");pass.setText("");}});box.addView(title);box.addView(sub);box.addView(touch);box.addView(pass,new LinearLayout.LayoutParams(-1,-2));box.addView(unlock);authView=box;WindowManager.LayoutParams p=lp(-1,-2,Gravity.CENTER);p.flags=WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL;wm.addView(authView,p);pass.requestFocus();}
private void unlock(){if(authView!=null){try{wm.removeView(authView);}catch(Exception ignored){}authView=null;}} private void hideAll(){removeIcon();if(authView!=null){try{wm.removeView(authView);}catch(Exception ignored){}authView=null;}}
@Override public int onStartCommand(Intent intent,int flags,int id){if(getSharedPreferences("fastlock",MODE_PRIVATE).getBoolean("active",false))handler.postDelayed(this::showIcon,250);return START_NOT_STICKY;}
@Override public void onDestroy(){hideAll();if(screenReceiver!=null){try{unregisterReceiver(screenReceiver);}catch(Exception ignored){}}super.onDestroy();}@Override public android.os.IBinder onBind(Intent intent){return null;}
}