package com.infinix.smart10.fastlock;
import android.app.*; import android.content.*; import android.net.Uri; import android.os.Bundle; import android.provider.Settings; import android.view.Gravity; import android.widget.*;
public class MainActivity extends Activity {
 private static final int OVERLAY_REQ=4101,WALLPAPER_REQ=4102; private android.content.SharedPreferences prefs;
 @Override public void onCreate(Bundle s){super.onCreate(s);prefs=getSharedPreferences("fastlock",MODE_PRIVATE);buildUi();}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(36,48,36,32);root.setBackgroundColor(0xFF080A0F);
 TextView title=new TextView(this);title.setText("FastLockApp");title.setTextColor(0xFFF2F2F2);title.setTextSize(28);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,-2));
 TextView status=new TextView(this);status.setText("\nFastLock layer: "+(prefs.getBoolean("active",false)?"ACTIVE":"OFF")+"\n\nFastLock PIN: "+(prefs.contains("passcode_hash")?"Set":"Not set")+"\nFastLock Fingerprint: "+(prefs.getBoolean("app_fingerprint_set",false)?"Set":"Not set")+"\nWallpaper: "+(prefs.getString("wallpaper_uri","").isEmpty()?"Default":"Selected")+"\n\nFastLock credentials are separate from Android's device credentials.");status.setTextColor(0xFFB9BEC8);status.setTextSize(16);status.setGravity(Gravity.CENTER);root.addView(status,new LinearLayout.LayoutParams(-1,0,1));
 Button wallpaper=new Button(this);wallpaper.setText("Choose FastLock Wallpaper");wallpaper.setOnClickListener(v->chooseWallpaper());root.addView(wallpaper,new LinearLayout.LayoutParams(-1,-2));
 Button setup=new Button(this);setup.setText("Set / change FastLock PIN");setup.setOnClickListener(v->showPasscodeDialog());root.addView(setup,new LinearLayout.LayoutParams(-1,-2));
 Button finger=new Button(this);finger.setText(prefs.getBoolean("app_fingerprint_set",false)?"Change FastLock Fingerprint":"Set up FastLock Fingerprint");finger.setOnClickListener(v->startActivityForResult(new Intent(this,FingerprintSetupActivity.class),88));root.addView(finger,new LinearLayout.LayoutParams(-1,-2));
 Button activate=new Button(this);activate.setText(prefs.getBoolean("active",false)?"STOP FASTLOCK":"ACTIVATE FASTLOCK");activate.setOnClickListener(v->toggleFastLock());root.addView(activate,new LinearLayout.LayoutParams(-1,-2));
 TextView note=new TextView(this);note.setText("\nWhen active, FastLock watches screen lock/wake events and shows its own layer. Authentication only dismisses FastLock; Android's real Keyguard remains in control. FastLock is disabled automatically after a reboot.");note.setTextColor(0xFF777D88);note.setGravity(Gravity.CENTER);root.addView(note,new LinearLayout.LayoutParams(-1,-2));setContentView(root);}
 private void toggleFastLock(){if(prefs.getBoolean("active",false)){prefs.edit().putBoolean("active",false).putBoolean("fastlock_authenticated",false).apply();stopService(new Intent(this,FastOverlayService.class));buildUi();return;}if(!prefs.contains("passcode_hash")||!prefs.getBoolean("app_fingerprint_set",false)){Toast.makeText(this,"Set your FastLock PIN and Fingerprint first.",Toast.LENGTH_LONG).show();return;}if(!Settings.canDrawOverlays(this)){startActivityForResult(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())),OVERLAY_REQ);return;}prefs.edit().putBoolean("active",true).putBoolean("fastlock_authenticated",false).apply();startLayer();buildUi();}
 private void chooseWallpaper(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,WALLPAPER_REQ);}
 private void showPasscodeDialog(){final EditText input=new EditText(this);input.setHint("4–12 digit FastLock PIN");input.setInputType(2);input.setTextColor(0xFFFFFFFF);input.setHintTextColor(0xFF777D88);new AlertDialog.Builder(this).setTitle("Create FastLock PIN").setMessage("This PIN belongs only to FastLockApp.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String value=input.getText().toString();if(value.length()<4||value.length()>12){Toast.makeText(this,"Use 4–12 digits",Toast.LENGTH_SHORT).show();return;}String salt=java.util.UUID.randomUUID().toString();prefs.edit().putString("passcode_salt",salt).putString("passcode_hash",hash(value,salt)).apply();Toast.makeText(this,"FastLock PIN saved",Toast.LENGTH_SHORT).show();buildUi();}).show();}
 private String hash(String value,String salt){try{javax.crypto.spec.PBEKeySpec spec=new javax.crypto.spec.PBEKeySpec(value.toCharArray(),salt.getBytes(java.nio.charset.StandardCharsets.UTF_8),120000,256);byte[] out=javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();return android.util.Base64.encodeToString(out,android.util.Base64.NO_WRAP);}catch(Exception e){throw new IllegalStateException(e);}}
 private void startLayer(){Intent i=new Intent(this,FastOverlayService.class);if(android.os.Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==WALLPAPER_REQ&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri uri=d.getData();try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);prefs.edit().putString("wallpaper_uri",uri.toString()).apply();Toast.makeText(this,"FastLock wallpaper saved",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Wallpaper could not be saved",Toast.LENGTH_SHORT).show();}}else if(r==OVERLAY_REQ&&Settings.canDrawOverlays(this)&&prefs.getBoolean("active",false))startLayer();buildUi();}
}