package com.infinix.smart10.fastlock;

import android.app.Activity; import android.app.AlertDialog; import android.content.Intent; import android.net.Uri; import android.os.Bundle; import android.provider.Settings; import android.view.Gravity; import android.widget.*;

public class MainActivity extends Activity {
private static final int OVERLAY_REQ=4101; private android.content.SharedPreferences prefs;
@Override public void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("fastlock",MODE_PRIVATE);buildUi();}
private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(48,60,48,40);root.setBackgroundColor(0xFF080A0F);
TextView title=new TextView(this);title.setText("FastLockApp");title.setTextColor(0xFFF2F2F2);title.setTextSize(28);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,-2));
TextView status=new TextView(this);status.setText("\nBottom app-owned lock layer\n\nFastLock PIN: "+(prefs.contains("passcode_hash")?"Set":"Not set")+"\nFastLock Fingerprint: "+(prefs.getBoolean("app_fingerprint_set",false)?"Set":"Not set")+"\n\nThese credentials exist only inside FastLockApp. Nothing is enrolled into Android's phone fingerprint settings.");status.setTextColor(0xFFB9BEC8);status.setTextSize(16);status.setGravity(Gravity.CENTER);root.addView(status,new LinearLayout.LayoutParams(-1,0,1));
Button setup=new Button(this);setup.setText("Set / change FastLock PIN");setup.setOnClickListener(v->showPasscodeDialog());root.addView(setup,new LinearLayout.LayoutParams(-1,-2));
Button finger=new Button(this);finger.setText(prefs.getBoolean("app_fingerprint_set",false)?"Change FastLock Fingerprint":"Set up FastLock Fingerprint");finger.setOnClickListener(v->{startActivityForResult(new Intent(this,FingerprintSetupActivity.class),88);});root.addView(finger,new LinearLayout.LayoutParams(-1,-2));
Button activate=new Button(this);activate.setText(prefs.getBoolean("active",false)?"Deactivate bottom lock layer":"Activate bottom lock layer");activate.setOnClickListener(v->{if(!prefs.contains("passcode_hash")||!prefs.getBoolean("app_fingerprint_set",false)){Toast.makeText(this,"Set both your FastLock PIN and FastLock Fingerprint first",Toast.LENGTH_LONG).show();return;}boolean active=!prefs.getBoolean("active",false);prefs.edit().putBoolean("active",active).apply();if(active){if(!Settings.canDrawOverlays(this)){startActivityForResult(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())),OVERLAY_REQ);return;}startLayer();}else stopService(new Intent(this,FastOverlayService.class));buildUi();});root.addView(activate,new LinearLayout.LayoutParams(-1,-2));
TextView note=new TextView(this);note.setText("\nFastLock Fingerprint is an app-only touch-pattern credential. It does not access, enroll, copy, or modify your phone's fingerprint system.\n\nAndroid still controls the actual system lock screen.");note.setTextColor(0xFF777D88);note.setGravity(Gravity.CENTER);root.addView(note,new LinearLayout.LayoutParams(-1,-2));setContentView(root);}
private void showPasscodeDialog(){final EditText input=new EditText(this);input.setHint("4–12 digit FastLock PIN");input.setInputType(2);input.setTextColor(0xFFFFFFFF);input.setHintTextColor(0xFF777D88);new AlertDialog.Builder(this).setTitle("Create FastLock PIN").setMessage("This PIN belongs only to FastLockApp.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String value=input.getText().toString();if(value.length()<4||value.length()>12){Toast.makeText(this,"Use 4–12 digits",Toast.LENGTH_SHORT).show();return;}android.content.SharedPreferences.Editor e=prefs.edit();String salt=java.util.UUID.randomUUID().toString();e.putString("passcode_salt",salt);e.putString("passcode_hash",hash(value,salt));e.apply();Toast.makeText(this,"FastLock PIN saved",Toast.LENGTH_SHORT).show();buildUi();}).show();}
private String hash(String value,String salt){try{javax.crypto.spec.PBEKeySpec spec=new javax.crypto.spec.PBEKeySpec(value.toCharArray(),salt.getBytes(java.nio.charset.StandardCharsets.UTF_8),120000,256);byte[] out=javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();return android.util.Base64.encodeToString(out,android.util.Base64.NO_WRAP);}catch(Exception e){throw new IllegalStateException(e);}}
private void startLayer(){Intent i=new Intent(this,FastOverlayService.class);if(android.os.Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
@Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==OVERLAY_REQ&&Settings.canDrawOverlays(this)&&prefs.getBoolean("active",false))startLayer();buildUi();}
}